# Generated by Django 5.0.2 on 2024-02-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/photos/', verbose_name='Фото'),
        ),
    ]
